{% set name = "nebula" %}
{% set version = "1.9.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/slackhq/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7feb8337a8ce791bb97211a70fddfc9cb936e2a9bfbb3bc8ac714c868da3fc86
  patches:
    - go_install_cross.patch  # [unix]
build:
  number: 0

requirements:
  build:
    - {{ compiler("go") }}
    - make  # [not win]
    - m2-make  # [win]
    - go-licenses

test:
  commands:
    - nebula -help
    - nebula-cert ca -name "Company"

about:
  home: https://github.com/slackhq/nebula
  summary: Nebula is a scalable overlay networking tool with a focus on performance, simplicity and security.
  description: |
    Nebula lets you seamlessly connect computers anywhere in the world.
    Nebula is portable, and runs on Linux, OSX, Windows, iOS, and Android.
    It can be used to connect a small number of computers, 
    but is also able to connect tens of thousands of computers.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - library_licenses/

extra:
  recipe-maintainers:
    - MichaelKora
    - wolfv
